#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Web.Admin.Views.NgView.configuration
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/NgView/configuration/index.cshtml")]
    public partial class index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public index()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<h2>Configuration summary</h2>
<p>Below is a summary of the data held in SingularConfigurationFactory.Current</p>
<h3>Applications (count = {{ factoryData.Applications.length }})</h3>
<h4 ng-repeat-start=""app in factoryData.Applications"">{{ app.Name }}</h4>
<table class=""sg-table"" ng-repeat-end>
    <tr>
        <th>Application Id</th>
        <td>{{ app.ApplicationId }}</td>
    </tr>
    <tr>
        <th>Admin sections</th>
        <td>
            <ul ng-repeat=""sec in app.AdminSections"">
                <li>{{ sec.Name + "" / "" + sec.Controller + "" / "" + sec.Action }}</li>
            </ul>
        </td>
    </tr>
    <tr>
        <th>Is Master Application</th>
        <td>{{ app.IsMasterApplication }}</td>
    </tr>
</table>
");


        }
    }
}
#pragma warning restore 1591
