#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Web.Admin.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 1 "..\..\Views\Home\Index.cshtml"
    using System.Security.AccessControl;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Home\Index.cshtml"
    using Singular.Web.Admin.Controllers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Home\Index.cshtml"
    using Singular.Web.Admin.Defaults;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Home\Index.cshtml"
    using Singular.Web.Common;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {





            
            #line 5 "..\..\Views\Home\Index.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta name=\"viewport\" content=\"width=dev" +
"ice-width\" />\r\n    <title>TBC title from object</title>\r\n    <script> window.ROO" +
"T_URL = \'");


            
            #line 15 "..\..\Views\Home\Index.cshtml"
                           Write(Url.Content("~/"));

            
            #line default
            #line hidden
WriteLiteral(@"';</script>
</head>
    <body ng-app=""Singular.Application"">
        <header>
            <h1>Singular CMS</h1>
        </header>
        <ng-include src=""'/Singular/NgView/partials/_nav/'""></ng-include>
        <section sg-view="""">
        </section>
        <!-- ANGULAR -->
        ");


            
            #line 25 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.ANGULAR_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 26 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.ANGULAR_ROUTE_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <!-- SINGULAR APP JS -->\r\n        ");


            
            #line 29 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.SINGULAR_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n        <!-- CONTROLLERS -->\r\n        ");


            
            #line 32 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.NAV_CONTROLLER_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 33 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.HOME_CONTROLLER_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 34 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.SYSTEM_CONTROLLER_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 35 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.CONFIGURATION_CONTROLLER_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n        <!-- DIRECTIVES -->\r\n        ");


            
            #line 38 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.SG_VIEW_DIRECTIVE_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n        <!-- SERVICES -->\r\n        ");


            
            #line 41 "..\..\Views\Home\Index.cshtml"
    Write(Html.EmbeddedInclude<NgViewController>(SingularAdminResources.CONFIG_DATA_SERVICE_MIN_JS, IncludeType.JavaScript));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
